name: Deploy Portfolio

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    # working-directory 제거
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./dev_nodejs_react/VITE_react/portfolio
      - name: Build
        run: npm run build
        working-directory: ./dev_nodejs_react/VITE_react/portfolio
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}  # 이렇게 변경
          publish_dir: ./dev_nodejs_react/VITE_react/portfolio/dist
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     submodules: false  # submodule 무시
